# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nuxt_nuxt
      # MYSQL_USER: nuxt_nuxt
      # MYSQL_PASSWORD: nuxt@6688