# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./logs:/logs
    restart: always
    environment:
      POSTGRES_USER: nuxt_nuxt
      POSTGRES_PASSWORD: 123456
      # MYSQL_USER: nuxt_nuxt
      # MYSQL_PASSWORD: nuxt@6688